### ISSUE TITLE
Portfolio Checklist

### ISSUE THREAD

**Issue by DavidLagou** [DavidLagou/portfolio-website#1]
# Portfolio Checklist

## Legend 
- Browsers
- Code
- Design

### Browsers

- [ ] #1 Compatible with all devices 

- [ ] #2 CSS grid works on all browsers  

### Code

- [ ] #3 All CSS have proper naming conventions 
- [ ] #4 CSS breakpoints are established and fully-functional

- [ ] All images have ALT tags.

### Design

- [ ] All headers have proper contrast 

- [ ] Buttons to Github on every single page
